apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::967481731151:role/jenkins-role
      username: jenkins-role
      groups: 
        - system:masters


        