---
# tasks file for roles/filebeat
- name:  Filebeat Download
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.11.0-amd64.deb
    dest: /home/ubuntu/filebeat-oss-7.11.0-amd64.deb
 

- name:  Filebeat installation
  apt:
    deb: /home/ubuntu/filebeat-oss-7.11.0-amd64.deb
  become: yes


- name: Add filebeat config file
  template:
    src: ./files/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  become: yes
  notify: restart filebeat


- name: Add Filebeat K8s config file
  template:
    src: ./files/filebeat_k8s.yml
    dest: /home/ubuntu/filebeat_k8s.yml
  when: tags['role'] == 'jenkins_slave'
  notify: restart filebeat 

# - name: Copy Filebeat K8s config file
#   copy:
#     src: ./files/filebeat_k8s.yml
#     dest: /home/ubuntu/filebeat_k8s.yml
#   when: tags['role'] == 'Jemkins Slave'
#   notify: restart filebeat   

- name: Deploy filebeat on K8s
  shell: kubectl apply -f /home/ubuntu/filebeat_k8s.yml
  ignore_errors: true
  when: tags['role'] == 'jenkins_slave'

- name: Start filebeat service
  ansible.builtin.service:
    name: filebeat
    state: started
  become: yes 