filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/auth.log
     # - /var/log/cloud-init-output.log
filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.dashboards.enabled: false
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
output.elasticsearch:
  hosts: ["elastic_search.service.consul:9200"]
  index: "filebeat-%{[agent.version]}-%{[agent.name]}-%{+yyyy.MM.dd}"