---
- name: configuration for Ellastic Search servers 
  hosts: 
    _elastic_search, 
  remote_user: ubuntu
  vars:
     ansible_ssh_private_key_file: "../terraform/keys/logging_key.pem"
  roles:
    - consul 
    - filebeat
    - node_exporter
  
  