plugin: aws_ec2
regions:
  - "us-east-2"
keyed_groups:
  #- key: tags.Name
  - key: tags.role
  #- key: tags.environment
filters:
  instance-state-name : running
  tag-key: role
compose:
  ansible_host: private_ip_address
